### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by rtroilo** [ElJocho/java_project#1]
I just push f64f5ac the initial setup. 
It included a .gitignore and the example spring rest project. This should work for all of you.

Please, for the geoguesser application use a different package(path) then the example.
The package path to use is :
javaintro.ws21.geoguesser
```
├── src
│   ├── main
│   │   ├── java
│   │   │   └── javaintro
│   │   │       └── ws21
│   │   │           └── geoguesser
│   │   │               └── GeoGuesserApplication.java
```

In case it makes problems to have multiple `@SpringBootApplication` in the same project. Just delete the `com.example....` part.

**Comment by ElJocho** [comment]
@rtroilo we are having trouble with the geo-operations (distance and contains) in java. Are there any easy to install libraries out there that can help with this? We tried gdal/ogr but it throws weird errors.. Otherwise it would also be possible to do them via hibernate in postgis, but here we are stuck as well, since we do not know how to do query's like "select st_distance(point, polygon)" with the hibernate interface..

Super ugly (imo) solution with geotools can be found [here](https://github.com/ElJocho/java_project/blob/main/src/main/java/javaintro/ws21/geoguesser/utils/PointCalculator.java) but ill eat a broom if there is not an easier solution.
